sudo: required
services:
    - docker

before_install:
    - docker build -t cse2018/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true cse2018/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-2-190207213771"
    bucket_path: "docker-react"
    access_key_id: 
        secure: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
    on:
        branch: master
        
        